src/Entity/Publication.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PublicationRepository")
 */
class Publication
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;
    
    /**
     * @var User
     * clé étrangère vers user
     * inversedBy doit être ajouté quand on a ajouté
     * un OneToMany (facultatif)
     * dans la classe User sur l'attribut publications
     * @ORM\ManyToOne(targetEntity="User", inversedBy="publications")
     * non null
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    public function getId()
    {
        return $this->id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }
    
    public function getAuthor()
    {
        return $this->author;
    }

    public function setAuthor(User $author)
    {
        $this->author = $author;
        return $this;
    }
    
    /**
     * 
     * @return string Le nom complet de l'auteur
     */
    public function getAuthorFullname()
    {
        if (!is_null($this->author)) {
            return $this->author->getFirstname()
                . ' ' . $this->author->getLastname();
        }
    }
}

src/Controller/DoctrineController.php
<?php

namespace App\Controller;

use App\Entity\Group;
use App\Entity\Publication;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/doctrine")
 */
class DoctrineController extends Controller
{
    /**
     * @Route("/")
     */
    public function index()
    {
        // gestionnaire d'entités de Doctrine
        $em = $this->getDoctrine()->getManager();
        // Retourne un objet User dont les attributs
        // sont settés à partir de la bdd
        // User avec l'id 1
        $user = $em->find(User::class, 1);
        // en version longue :
        // $repository = $em->getRepository(User::class);
        // $user = $repository->find(1);
        
        // s'il n'y a pas d'utilisateur avec l'id 1 en bdd
        // la méthode find retourne null
        if (is_null($user)) {
            // lance une 404
            throw new NotFoundHttpException();
        }
        
        return $this->render(
            'doctrine/index.html.twig',
            [
                'user' => $user
            ]
        );
    }
    
    /**
     * @Route("/create-user")
     */
    public function createUser(Request $request)
    {
        // si on a reçu du POST
        if ($request->isMethod('POST')) {
            // var_dump($_POST)
            dump($request->request->all());
            $data = $request->request->all();
            
            // on instancie un nouvel objet User
            // et on sette ses attributs avec les données 
            // que l'on a reçu du formulaire
            $user = new User();
            
            $user
                ->setLastname($data['lastname'])
                ->setFirstname($data['firstname'])
                ->setEmail($data['email'])
                // le setter de birthdate attend un objet Datetime
                ->setBirthdate(new \DateTime($data['birthdate']))
            ;
            
            $em = $this->getDoctrine()->getManager();
            // dit qu'il faudra enregistrer l'utilisateur
            // en bdd au prochain appel de la méthode flush()
            $em->persist($user);
            // enregistrement effectif
            $em->flush();
        }
        
        return $this->render(
            'doctrine/create_user.html.twig'
        );
    }
    
    /**
     * @Route("/list-user")
     */
    public function listUser()
    {
        $em = $this->getDoctrine()->getManager();
        // $repository contient une instance
        // de App\Repository\UserRepository
        $repository = $em->getRepository(User::class);
        // retourne tous les utilisateurs de la table user
        // sous forme d'un tableau d'objets User
        $users = $repository->findAll();
        
        dump($users);
        
        return $this->render(
            'doctrine/list_user.html.twig',
            [
                'users' => $users
            ]
        );
    }
    
    /**
     * @Route("/search-email/{email}")
     */
    public function searchEmail($email)
    {
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository(User::class);
        // findOneBy() quand on est sûr qu'il
        // y a un résultat max (sur un index unique)
        // retourne un objet User ou null
        $user = $repository->findOneBy([
            'email' => $email
        ]);
        
        if (is_null($user)) {
            throw new NotFoundHttpException();
        }
        
        return $this->render(
            'doctrine/index.html.twig',
            [
                'user' => $user
            ]
        );
    }
    
    /**
     * 
     * @Route("/search-lastname/{lastname}")
     */
    public function searchLastname($lastname)
    {
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository(User::class);
        
        // retourne un tableau d'objets User
        // filtré sur le nom de famille
        // S'il n'y a aucun user en bdd avec ce nom
        // de famille, retourne un tableau vide
        $users = $repository->findBy([
            'lastname' => $lastname
        ]);
        
        dump($users);
        
        return $this->render(
            'doctrine/list_user.html.twig',
            [
                'users' => $users
            ]
        );
    }
    
    /**
     * Le paramètre dans l'url s'appelle id
     * comme la clé primaire de la table user
     * En typant User le paramètre passé à la méthode
     * d'action, je récupère dans $author un objet User
     * qui a cet id en bdd
     * C'est le composant ParamConverter qui fait ça
     * 
     * @Route("/publication/author/{id}")
     */
    public function publicationsByAuthor(User $author)
    {
        dump($author);
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository(Publication::class);
        
        $publications = $repository->findBy([
            'author' => $author
        ]);

        dump($publications);
        
        return $this->render(
            'doctrine/publications.html.twig',
            [
                'publications' => $publications
            ]
        );
    }
    /**
     * @Route("/author/{id}/publications")
     */
    public function userPublications(User $user)
    {
        // en demandant le contenu de l'attribut $publications
        // d'un objet User, Doctrine va automatiquement
        // faire une requête en bdd
        // pour y mettre les publications liées à cet utilisateur
        // grâce à l'annotation @ORM\OneToMany sur
        // l'attribut dans la classe
        
        return $this->render(
            'doctrine/user_publications.html.twig',
            [
                'user' => $user
            ]
        );
    }
    
    /**
     * 
     * @Route("/user-with-publication")
     */
    public function userWithPublication(Request $request)
    {
        if ($request->isMethod('POST')) {
            $data = $request->request->all();
            $user = new User();
            $user
                ->setLastname($data['lastname'])
                ->setFirstname($data['firstname'])
                ->setEmail($data['email'])
                ->setBirthdate(new \DateTime($data['birthdate']))
            ;
            
            $publication = new Publication();
            
            $publication
                ->setTitle($data['title'])
                ->setContent($data['content'])
            ;
            
            $user->addPublication($publication);
            
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            // grâce à cascade={"persist"} ajouté dans
            // l'annotation OneToMany sur l'attribut $publications
            // de la classe User plus besoin d'appeler la méthode persist()
            // sur la publication pour qu'elle soit enregistrée en bdd
            
            //$em->persist($publication);
            $em->flush();
        }
        
        return $this->render(
            'doctrine/user_with_publication.html.twig'
        );
    }
    
    /**
     * @Route("/users/group/{id}")
     */
    public function usersByGroup(Group $group)
    {
        return $this->render(
            'doctrine/users_by_group.html.twig',
            [
                'group' => $group
            ]
        );
    }
}

templates/doctrine/create_user.html.twig
{# doctrine/create_user.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    <form method="post">
        <div>
            <label>Nom</label>
            <input type="text" name="lastname">
        </div>
        <div>
            <label>Prénom</label>
            <input type="text" name="firstname">
        </div>
        <div>
            <label>Email</label>
            <input type="text" name="email">
        </div>
        <div>
            <label>Date de naissance</label>
            <input type="text" name="birthdate">
        </div>
        <div>
            <button type="submit">Enregistrer</button>
        </div>
    </form>
{% endblock %}

templates/doctrine/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <p>Bonjour {{ user.firstname }} {{ user.lastname }}</p>
{% endblock %}

templates/doctrine/list_user.html.twig
{# doctrine/list_user.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    {#
    Lister les informations des utilisateurs
    dans un tableau HTML,
    la date de naissance en format français
    #}
    <table>
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Email</th>
            <th>Date de naissance</th>
        </tr>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.lastname }}</td>
                <td>{{ user.firstname }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.birthdate|date('d/m/Y') }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/doctrine/publications.html.twig
{# doctrine/publications.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    <table>
        <tr>
            <th>Id</th>
            <th>Titre</th>
            <th>Contenu</th>
            <th>Auteur</th>
        </tr>
        {% for publication in publications %}
            <tr>
                <td>{{ publication.id }}</td>
                <td>{{ publication.title }}</td>
                <td>{{ publication.content }}</td>
                {# méthode getAuthorFullname() de l'entité Publication #}
                <td>{{ publication.authorFullname }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/doctrine/user_publications.html.twig
{# doctrine/user_publications.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    <p>{{ user.firstname }} {{ user.lastname }}</p>
    <table>
        <caption>Publications</caption>
        <tr>
            <th>Id</th>
            <th>Titre</th>
            <th>Contenu</th>
        </tr>
        {% for publication in user.publications %}
            <tr>
                <td>{{ publication.id }}</td>
                <td>{{ publication.title }}</td>
                <td>{{ publication.content }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/doctrine/user_with_publication.html.twig
{# doctrine/user_with_publication.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    <form method="post">
        <div>
            <label>Nom</label>
            <input type="text" name="lastname">
        </div>
        <div>
            <label>Prénom</label>
            <input type="text" name="firstname">
        </div>
        <div>
            <label>Email</label>
            <input type="text" name="email">
        </div>
        <div>
            <label>Date de naissance</label>
            <input type="text" name="birthdate">
        </div>
        <div>
            <label>Titre de la publication</label>
            <input type="text" name="title">
        </div>
        <div>
            <label>Contenu de la publication</label>
            <textarea name="content"></textarea>
        </div>
        <div>
            <button type="submit">Enregistrer</button>
        </div>
    </form>
{% endblock %}

templates/doctrine/users_by_group.html.twig
{# doctrine/users_by_group.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    {#
    Parce que la classe Group contient
    une méthode __toString(), on peut directement
    afficher l'objet
    C'est ce que retourne cette méthode qui est affiché
    #}
    <p>{{ group }}</p>
    
    <table>
        <tr>
            <th>Utilisateur</th>
        </tr>
        {% for user in group.users %}
            <tr>
                <td>{{ user }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}